-- AlterTable
ALTER TABLE "DailyHealthLog" ADD COLUMN IF NOT EXISTS "waterIntake" INTEGER;

-- AlterTable
ALTER TABLE "UserNutritionTarget" ADD COLUMN IF NOT EXISTS "exerciseCalorieFactor" DOUBLE PRECISION NOT NULL DEFAULT 0.5;
ALTER TABLE "UserNutritionTarget" ADD COLUMN IF NOT EXISTS "waterGoalMl" INTEGER NOT NULL DEFAULT 2500;
ALTER TABLE "UserNutritionTarget" ADD COLUMN IF NOT EXISTS "waterTrackingEnabled" BOOLEAN NOT NULL DEFAULT false;
