package com.runflow2.app.core.export

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.runflow2.app.core.util.DistanceUnit
import com.runflow2.app.core.util.Format
import com.runflow2.app.data.db.GoalEntity
import com.runflow2.app.data.db.WorkoutEntity
import com.runflow2.app.data.repo.date
import com.runflow2.app.data.repo.phase
import com.runflow2.app.data.repo.raceType
import com.runflow2.app.data.repo.type
import java.io.File
import java.io.OutputStream
import java.time.DayOfWeek

/**
 * Renders the active training plan as a PDF — the Android counterpart of the
 * web's plan export (`/api/public/plan/export`): a header block, then one
 * section per training week with a Date/Day/Type/Workout/Dist/Time/Pace table.
 * Layout math (grouping + row strings) is kept in [buildWeeks] so it is plain
 * unit-testable; only [export] touches Android graphics.
 */
class PlanPdfExporter(private val unit: DistanceUnit = DistanceUnit.METRIC) {

    data class Row(
        val date: String,
        val day: String,
        val type: String,
        val description: String,
        val distance: String,
        val time: String,
        val pace: String,
    )

    data class WeekBlock(
        val number: Int,
        val title: String,
        val phase: String,
        val totalDistance: String,
        val rows: List<Row>,
    )

    /** Groups workouts into ISO weeks (Mon–Sun) in schedule order. Pure Kotlin. */
    fun buildWeeks(workouts: List<WorkoutEntity>): List<WeekBlock> {
        val sorted = workouts.sortedBy { it.scheduledDate }
        val byMonday = sorted.groupBy { it.date().with(DayOfWeek.MONDAY) }
        return byMonday.entries.mapIndexed { i, (monday, weekWorkouts) ->
            WeekBlock(
                number = i + 1,
                title = "${Format.date(monday)} – ${Format.date(monday.plusDays(6))}",
                phase = weekWorkouts.first().phase().label,
                totalDistance = Format.distance(weekWorkouts.sumOf { it.targetDistanceKm ?: 0.0 }, unit),
                rows = weekWorkouts.map { w ->
                    Row(
                        date = Format.date(w.date()),
                        day = Format.dayShort(w.date().dayOfWeek),
                        type = w.type().label,
                        description = w.customName?.takeIf { it.isNotBlank() } ?: w.description,
                        distance = w.targetDistanceKm?.let { Format.distance(it, unit) } ?: "",
                        time = w.targetDurationSec?.let { Format.duration(it) } ?: "",
                        pace = w.targetPaceSecPerKm?.let { Format.pace(it.toDouble(), unit) } ?: "",
                    )
                },
            )
        }
    }

    /** Stable file name for the exported plan (mirrors the web export naming). */
    fun fileName(goal: GoalEntity): String = "runflow-${goal.raceType.lowercase()}-plan.pdf"

    /** Writes the plan PDF into `cache/exports/` and returns the file, ready to share. */
    fun exportToCache(context: Context, goal: GoalEntity, workouts: List<WorkoutEntity>): File {
        val dir = File(context.cacheDir, "exports").apply { mkdirs() }
        val file = File(dir, fileName(goal))
        file.outputStream().use { export(goal, workouts, it) }
        return file
    }

    fun export(goal: GoalEntity, workouts: List<WorkoutEntity>, out: OutputStream) {
        val weeks = buildWeeks(workouts)
        val doc = PdfDocument()

        val title = goal.name.ifBlank { "${goal.raceType().label} Training Plan" }
        val subtitle = "${goal.raceType().label} · Race date: ${Format.dateWithYear(Format.localDate(goal.raceDate))}"
        val meta = listOfNotNull(
            goal.targetTimeSec?.let { "Target ${Format.duration(it)}" },
            "Peak ${Format.distance(goal.weeklyKmGoal, unit)}/wk",
            "${goal.planWeeks} weeks",
        ).joinToString("  ·  ") + "  ·  Generated by RunFlow"

        val titlePaint = paint(20f, bold = true)
        val subtitlePaint = paint(11f, color = Color.DKGRAY)
        val metaPaint = paint(9f, color = Color.GRAY)
        val weekPaint = paint(11f, bold = true)
        val headerPaint = paint(8f, bold = true, color = Color.GRAY)
        val bodyPaint = paint(9f)

        var page = doc.startPage(pageInfo(1))
        var canvas = page.canvas
        var y = MARGIN.toFloat()
        var pageNo = 1

        fun newPage(keepWeekHeader: String? = null) {
            drawFooter(canvas, pageNo)
            doc.finishPage(page)
            pageNo++
            page = doc.startPage(pageInfo(pageNo))
            canvas = page.canvas
            y = MARGIN.toFloat()
            if (keepWeekHeader != null) {
                drawWeekHeader(canvas, y, keepWeekHeader, weekPaint, headerPaint)
                y += WEEK_HEADER_H
            }
        }

        // ---- title block ----
        canvas.drawText(title, MARGIN.toFloat(), y + 16f, titlePaint)
        y += 30f
        canvas.drawText(subtitle, MARGIN.toFloat(), y + 10f, subtitlePaint)
        y += 24f
        canvas.drawText(meta, MARGIN.toFloat(), y + 8f, metaPaint)
        y += 26f

        // ---- week blocks ----
        weeks.forEach { week ->
            if (y > PAGE_H - MARGIN - WEEK_HEADER_H - 3 * ROW_H) newPage()
            drawWeekHeader(canvas, y, "Week ${week.number} · ${week.phase} · ${week.title} · ${week.totalDistance}", weekPaint, headerPaint)
            y += WEEK_HEADER_H
            week.rows.forEach { row ->
                val lines = wrap(row.description, DESC_W, bodyPaint)
                val rowH = ROW_H + (lines.size - 1) * 11f
                if (y + rowH > PAGE_H - FOOTER_MARGIN) {
                    newPage("Week ${week.number} (cont.)")
                }
                drawRow(canvas, row, lines, y, bodyPaint)
                y += rowH
            }
            y += 10f
        }
        drawFooter(canvas, pageNo)
        doc.finishPage(page)
        try {
            doc.writeTo(out)
        } finally {
            doc.close()
        }
    }

    // ---- layout constants (A4 at 72 dpi) ----
    private companion object {
        const val PAGE_W = 595
        const val PAGE_H = 842
        const val MARGIN = 42
        const val FOOTER_MARGIN = 60

        // column x positions (left-aligned unless noted)
        const val X_DATE = 42f
        const val X_DAY = 92f
        const val X_TYPE = 122f
        const val X_DESC = 208f
        const val X_DIST_R = 462f // right-aligned
        const val X_TIME_R = 508f
        const val X_PACE_R = 553f
        const val DESC_W = 215f
        const val ROW_H = 16f
        const val WEEK_HEADER_H = 34f
    }

    private fun pageInfo(n: Int) = PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, n).create()

    private fun drawWeekHeader(canvas: Canvas, topY: Float, text: String, weekPaint: Paint, headerPaint: Paint) {
        canvas.drawText(text, X_DATE, topY + 12f, weekPaint)
        val y2 = topY + 24f
        canvas.drawText("Date", X_DATE, y2, headerPaint)
        canvas.drawText("Day", X_DAY, y2, headerPaint)
        canvas.drawText("Type", X_TYPE, y2, headerPaint)
        canvas.drawText("Workout", X_DESC, y2, headerPaint)
        drawRight(canvas, "Dist", X_DIST_R, y2, headerPaint)
        drawRight(canvas, "Time", X_TIME_R, y2, headerPaint)
        drawRight(canvas, "Pace", X_PACE_R, y2, headerPaint)
    }

    private fun drawRow(canvas: Canvas, row: Row, descLines: List<String>, topY: Float, paint: Paint) {
        val base = topY + 11f
        canvas.drawText(row.date, X_DATE, base, paint)
        canvas.drawText(row.day, X_DAY, base, paint)
        canvas.drawText(row.type, X_TYPE, base, paint)
        descLines.forEachIndexed { i, line ->
            canvas.drawText(line, X_DESC, base + i * 11f, paint)
        }
        drawRight(canvas, row.distance, X_DIST_R, base, paint)
        drawRight(canvas, row.time, X_TIME_R, base, paint)
        drawRight(canvas, row.pace, X_PACE_R, base, paint)
    }

    private fun drawFooter(canvas: Canvas, pageNo: Int) {
        val p = paint(8f, color = Color.GRAY)
        canvas.drawText("RunFlow · runflow.schuelken.uk", MARGIN.toFloat(), PAGE_H - 30f, p)
        val label = "$pageNo"
        val w = p.measureText(label)
        canvas.drawText(label, PAGE_W - MARGIN - w, PAGE_H - 30f, p)
    }

    private fun drawRight(canvas: Canvas, text: String, rightX: Float, y: Float, paint: Paint) {
        if (text.isBlank()) return
        canvas.drawText(text, rightX - paint.measureText(text), y, paint)
    }

    private fun wrap(text: String, width: Float, paint: Paint, maxLines: Int = 2): List<String> {
        val t = text.ifBlank { return listOf("") }
        val lines = mutableListOf<String>()
        var rest = t
        while (rest.isNotEmpty() && lines.size < maxLines) {
            val measured = paint.breakText(rest, true, width, null)
            if (measured >= rest.length) {
                lines.add(rest)
                return lines
            }
            // break on a space when possible
            val cut = rest.lastIndexOf(' ', measured).takeIf { it > 0 } ?: measured
            lines.add(rest.substring(0, cut).trimEnd())
            rest = rest.substring(cut).trimStart()
        }
        if (rest.isNotEmpty() && lines.size == maxLines) {
            // ellipsize the last line
            var last = lines.removeAt(lines.size - 1) + " " + rest
            while (paint.measureText(last + "…") > width && last.length > 1) {
                last = last.dropLast(1)
            }
            lines.add(last.trimEnd() + "…")
        }
        return lines
    }

    private fun paint(size: Float, bold: Boolean = false, color: Int = Color.BLACK): Paint =
        Paint(Paint.ANTI_ALIAS_FLAG).apply {
            textSize = size
            this.color = color
            typeface = if (bold) Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD) else Typeface.SANS_SERIF
        }
}
