package com.runflow2.app.domain.plan

/**
 * Wizard steps, in display order. The plan engine is NOT user-selectable:
 * signed in, the plan is generated by the server (the same engine as the
 * website) and falls back to the on-device port of that engine on any
 * failure; signed out or offline, the on-device engine is used directly —
 * it is the only local engine. Which engine produced the current plan is
 * shown on the plan screen. See PlanWizardScreen for the fallback chain.
 */
enum class WizardStep {
    EVENT_TYPE,
    RACE,
    DATE,
    CALIBRATION,
    TARGET,
    VOLUME,
    ADVANCED,
    SCHEDULE,
}

/** Event categories offered on the wizard's first screen. */
enum class EventCategory(val label: String) {
    RUN("Run"),
    ULTRA("Ultra"),
    TRIATHLON("Triathlon"),
    GENERAL("General fitness"),
}

object PlanMethodFlow {

    /**
     * Steps for a goal. The first screen always picks the event category
     * (Run / Ultra / Triathlon / General); the second screen picks the
     * specific race. A no-race goal (RaceType.NONE — general fitness) then
     * skips the race, date, calibration and target-time steps; a plan length
     * is picked on the volume step instead.
     */
    fun stepsFor(noRace: Boolean): List<WizardStep> = if (noRace) {
        listOf(WizardStep.EVENT_TYPE, WizardStep.VOLUME, WizardStep.ADVANCED, WizardStep.SCHEDULE)
    } else {
        WizardStep.entries.toList()
    }
}
