-- CreateEnum
CREATE TYPE "PlanSport" AS ENUM ('RUN', 'TRIATHLON');

-- CreateEnum
CREATE TYPE "PlanCreationMode" AS ENUM ('EXPERT_MANUAL', 'GUIDED', 'AI_ASSISTED', 'STANDARD_BUILDER', 'CSV_IMPORT');

-- CreateEnum
CREATE TYPE "GoalPriority" AS ENUM ('PRIMARY', 'SECONDARY', 'TUNE_UP', 'MILESTONE');

-- AlterEnum
ALTER TYPE "RaceType" ADD VALUE 'FIFTY_K';
ALTER TYPE "RaceType" ADD VALUE 'FIFTY_MILE';
ALTER TYPE "RaceType" ADD VALUE 'HUNDRED_K';
ALTER TYPE "RaceType" ADD VALUE 'HUNDRED_MILE';
ALTER TYPE "RaceType" ADD VALUE 'TWELVE_HOUR';
ALTER TYPE "RaceType" ADD VALUE 'TWENTY_FOUR_HOUR';
ALTER TYPE "RaceType" ADD VALUE 'BACKYARD_ULTRA';
ALTER TYPE "RaceType" ADD VALUE 'CUSTOM_DISTANCE';
ALTER TYPE "RaceType" ADD VALUE 'SPRINT_TRI';
ALTER TYPE "RaceType" ADD VALUE 'OLYMPIC_TRI';
ALTER TYPE "RaceType" ADD VALUE 'HALF_IRONMAN';
ALTER TYPE "RaceType" ADD VALUE 'FULL_IRONMAN';
ALTER TYPE "RaceType" ADD VALUE 'CUSTOM_TRI';

-- AlterEnum
ALTER TYPE "WorkoutType" ADD VALUE 'BRICK';
ALTER TYPE "WorkoutType" ADD VALUE 'OPEN_WATER_SWIM';
ALTER TYPE "WorkoutType" ADD VALUE 'LONG_RIDE';
ALTER TYPE "WorkoutType" ADD VALUE 'RIDE_INTERVALS';
ALTER TYPE "WorkoutType" ADD VALUE 'SWIM_DRILL';
ALTER TYPE "WorkoutType" ADD VALUE 'TRANSITION_PRACTICE';
ALTER TYPE "WorkoutType" ADD VALUE 'DOUBLE_DAY';

-- AlterEnum
ALTER TYPE "PlanPhase" ADD VALUE 'ENDURANCE';
ALTER TYPE "PlanPhase" ADD VALUE 'MENTAL_PREP';
ALTER TYPE "PlanPhase" ADD VALUE 'TUNE_UP';
ALTER TYPE "PlanPhase" ADD VALUE 'MAINTAIN';
