export const WORKOUT_COLORS: Record<string, { bg: string; text: string; dot: string }> = {
    EASY:         { bg: 'bg-workout-easy/10',         text: 'text-workout-easy',         dot: 'bg-workout-easy' },
    LONG_RUN:     { bg: 'bg-workout-long-run/10',     text: 'text-workout-long-run',     dot: 'bg-workout-long-run' },
    TEMPO:        { bg: 'bg-workout-tempo/10',        text: 'text-workout-tempo',        dot: 'bg-workout-tempo' },
    INTERVALS:    { bg: 'bg-workout-interval/10',     text: 'text-workout-interval',     dot: 'bg-workout-interval' },
    FARTLEK:      { bg: 'bg-workout-interval/10',     text: 'text-workout-interval',     dot: 'bg-workout-interval' },
    REPETITIONS:  { bg: 'bg-workout-interval/10',     text: 'text-workout-interval',     dot: 'bg-workout-interval' },
    RECOVERY:     { bg: 'bg-workout-recovery/10',     text: 'text-workout-recovery',     dot: 'bg-workout-recovery' },
    RACE:         { bg: 'bg-workout-race/10',         text: 'text-workout-race',         dot: 'bg-workout-race' },
    REST:         { bg: 'bg-foreground/10',           text: 'text-foreground-muted',     dot: 'bg-foreground/30' },
    RIDE:         { bg: 'bg-accent-blue/10',          text: 'text-accent-blue',          dot: 'bg-accent-blue' },
    SWIM:         { bg: 'bg-accent-blue/10',          text: 'text-accent-blue',          dot: 'bg-accent-blue' },
    STRENGTH:     { bg: 'bg-workout-strength/10',     text: 'text-workout-strength',     dot: 'bg-workout-strength' },
    CROSS_TRAIN:  { bg: 'bg-workout-easy/10',         text: 'text-workout-easy',         dot: 'bg-workout-easy' },
    OTHER:        { bg: 'bg-foreground/10',           text: 'text-foreground-muted',     dot: 'bg-foreground/30' },
    BRICK:        { bg: 'bg-workout-tempo/10',        text: 'text-workout-tempo',        dot: 'bg-workout-tempo' },
    OPEN_WATER_SWIM: { bg: 'bg-accent-blue/10',      text: 'text-accent-blue',          dot: 'bg-accent-blue' },
    LONG_RIDE:    { bg: 'bg-accent-blue/10',          text: 'text-accent-blue',          dot: 'bg-accent-blue' },
    RIDE_INTERVALS: { bg: 'bg-workout-interval/10',   text: 'text-workout-interval',     dot: 'bg-workout-interval' },
    SWIM_DRILL:   { bg: 'bg-accent-blue/10',          text: 'text-accent-blue',          dot: 'bg-accent-blue' },
    TRANSITION_PRACTICE: { bg: 'bg-workout-strength/10', text: 'text-workout-strength',  dot: 'bg-workout-strength' },
    DOUBLE_DAY:   { bg: 'bg-workout-interval/10',     text: 'text-workout-interval',     dot: 'bg-workout-interval' },
};
