import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import { buildExportPlan, exportFileName, PHASE_COLORS, TYPE_COLORS, type ExportPlan } from './plan-export';

/**
 * Server-side plan → PDF renderer (the "web engine" export the mobile app
 * uses when signed in): A4 pages, phase-colored week badges, colored type
 * pills and the same week tables as the web's plan export HTML.
 */

// A4 in PDF points
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 42;
const BOTTOM = 56;

// column x positions
const X_DATE = MARGIN;
const X_DAY = 92;
const X_TYPE = 122;
const X_DESC = 210;
const X_DIST_R = 462; // right-aligned
const X_TIME_R = 508;
const X_PACE_R = PAGE_W - MARGIN; // right-aligned
const DESC_W = 210;
const HEADER_BG = rgb(0.976, 0.98, 0.982); // #f9fafb
const LINE = rgb(0.898, 0.906, 0.922); // #e5e7eb
const GRAY = rgb(0.42, 0.447, 0.502); // #6b7280
const DARK = rgb(0.059, 0.09, 0.165); // #0f172a
const WHITE = rgb(1, 1, 1);

function hexToRgb(hex: string) {
    const v = hex.replace('#', '');
    return rgb(
        parseInt(v.slice(0, 2), 16) / 255,
        parseInt(v.slice(2, 4), 16) / 255,
        parseInt(v.slice(4, 6), 16) / 255,
    );
}

/**
 * StandardFonts are WinAnsi-encoded — pdf-lib THROWS on any character
 * outside cp1252 (emoji, CJK, …) drawn with them. Goal names and workout
 * descriptions are user/AI-authored, so replace anything unencodable
 * instead of failing the whole export.
 */
const WINANSI_UNENCODABLE = /[^\u0000-\u00FF\u0152\u0153\u0160\u0161\u0178\u017D\u017E\u2013\u2014\u2018\u2019\u201A\u201C\u201E\u2020\u2021\u2022\u2026\u2030\u2039\u203A\u20AC\u2122]/g;
function winAnsi(text: string): string {
    return (text ?? '').replace(WINANSI_UNENCODABLE, '?');
}

/** Wraps text to the width; maxLines with ellipsis on overflow. */
function wrap(text: string, width: number, font: PDFFont, size: number, maxLines: number): string[] {
    const t = winAnsi(text).replace(/\s+/g, ' ').trim();
    if (!t) return [''];
    const lines: string[] = [];
    let rest = t;
    while (rest.length && lines.length < maxLines) {
        if (font.widthOfTextAtSize(rest, size) <= width) {
            lines.push(rest);
            return lines;
        }
        let cut = rest.length;
        while (cut > 1 && font.widthOfTextAtSize(rest.slice(0, cut), size) > width) cut--;
        const space = rest.lastIndexOf(' ', cut);
        const at = space > 0 ? space : cut;
        lines.push(rest.slice(0, at).trimEnd());
        rest = rest.slice(at).trimStart();
    }
    if (rest.length && lines.length === maxLines) {
        let last = `${lines[lines.length - 1]} ${rest}`;
        while (last.length > 1 && font.widthOfTextAtSize(`${last}…`, width) > width) {
            last = last.slice(0, -1);
        }
        lines[lines.length - 1] = `${last.trimEnd()}…`;
    }
    return lines;
}

function drawRight(page: PDFPage, text: string, rightX: number, y: number, font: PDFFont, size: number, color = DARK) {
    if (!text || text === '-') return;
    page.drawText(text, { x: rightX - font.widthOfTextAtSize(text, size), y, size, font, color });
}

export async function buildPlanPdf(plan: ExportPlan): Promise<Uint8Array> {
    const doc = await PDFDocument.create();
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const bold = await doc.embedFont(StandardFonts.HelveticaBold);

    const pages: PDFPage[] = [];
    let page = doc.addPage([PAGE_W, PAGE_H]);
    pages.push(page);
    let y = PAGE_H - MARGIN;

    const addPage = () => {
        page = doc.addPage([PAGE_W, PAGE_H]);
        pages.push(page);
        y = PAGE_H - MARGIN;
    };

    // ---- title block (page 1 only) ----
    page.drawText(winAnsi(plan.goalName), { x: MARGIN, y: y - 20, size: 21, font: bold, color: DARK });
    y -= 34;
    page.drawText(winAnsi(`${plan.raceTypeLabel}  ·  Race date: ${plan.raceDate}`), {
        x: MARGIN, y: y - 10, size: 11, font, color: GRAY,
    });
    y -= 26;
    const meta = [
        plan.targetTime ? `Target ${plan.targetTime}` : null,
        plan.peakWeeklyKm ? `Peak ${plan.peakWeeklyKm} km/wk` : null,
        `${plan.planWeeks} weeks`,
    ].filter(Boolean).join('  ·  ');
    page.drawText(`${meta}  ·  Generated by RunFlow`, { x: MARGIN, y: y - 8, size: 9, font, color: GRAY });
    y -= 24;

    const drawWeekHeader = (week: ExportPlan['weeks'][number], continued: boolean) => {
        const phaseColor = hexToRgb(PHASE_COLORS[week.phase] ?? '#6b7280');
        const label = continued ? `Week ${week.weekNumber} (cont.)` : `Week ${week.weekNumber}`;
        const badgeW = bold.widthOfTextAtSize(label, 10) + 14;
        page.drawRectangle({ x: X_DATE, y: y - 13, width: badgeW, height: 16, color: phaseColor });
        page.drawText(label, { x: X_DATE + 7, y: y - 9, size: 10, font: bold, color: WHITE });
        const phaseText = week.phase.replace(/_/g, ' ');
        const chipW = font.widthOfTextAtSize(phaseText, 9) + 12;
        page.drawRectangle({ x: X_DATE + badgeW + 6, y: y - 12.5, width: chipW, height: 15, color: phaseColor, opacity: 0.15 });
        page.drawText(phaseText, { x: X_DATE + badgeW + 12, y: y - 9, size: 9, font, color: phaseColor });
        drawRight(page, winAnsi(week.dateRange), X_TIME_R - 6, y - 9, font, 9, GRAY);
        drawRight(page, `${week.totalDistanceKm} km`, X_PACE_R, y - 9, font, 9, GRAY);
        y -= 22;

        page.drawRectangle({ x: X_DATE - 4, y: y - 11, width: PAGE_W - 2 * MARGIN + 8, height: 14, color: HEADER_BG });
        page.drawText('Date', { x: X_DATE, y: y - 8, size: 7.5, font: bold, color: GRAY });
        page.drawText('Day', { x: X_DAY, y: y - 8, size: 7.5, font: bold, color: GRAY });
        page.drawText('Type', { x: X_TYPE, y: y - 8, size: 7.5, font: bold, color: GRAY });
        page.drawText('Workout', { x: X_DESC, y: y - 8, size: 7.5, font: bold, color: GRAY });
        drawRight(page, 'Dist', X_DIST_R, y - 8, bold, 7.5, GRAY);
        drawRight(page, 'Time', X_TIME_R, y - 8, bold, 7.5, GRAY);
        drawRight(page, 'Pace', X_PACE_R, y - 8, bold, 7.5, GRAY);
        y -= 18;
    };

    for (const week of plan.weeks) {
        let rowsDrawn = 0;
        // need room for the week header + at least one max-height (2-line) row
        if (y - 22 - 18 - 25 < BOTTOM) addPage();
        drawWeekHeader(week, rowsDrawn > 0);

        for (const row of week.rows) {
            const descLines = wrap(row.title, DESC_W, font, 8.5, 2);
            const rowH = 15 + (descLines.length - 1) * 10;
            if (y - rowH < BOTTOM) {
                addPage();
                drawWeekHeader(week, rowsDrawn > 0);
            }

            const base = y - 10;
            page.drawText(row.date, { x: X_DATE, y: base, size: 8.5, font, color: DARK });
            page.drawText(row.day, { x: X_DAY, y: base, size: 8.5, font, color: GRAY });

            const typeText = row.type.replace(/_/g, ' ');
            const typeColor = hexToRgb(TYPE_COLORS[row.type] ?? '#6b7280');
            const pillW = font.widthOfTextAtSize(typeText, 7) + 8;
            page.drawRectangle({ x: X_TYPE, y: base - 2.5, width: pillW, height: 11, color: typeColor });
            page.drawText(typeText, { x: X_TYPE + 4, y: base, size: 7, font: bold, color: WHITE });

            descLines.forEach((line, i) => {
                page.drawText(line, { x: X_DESC, y: base - i * 10, size: 8.5, font, color: DARK });
            });
            drawRight(page, row.distanceKm, X_DIST_R, base, font, 8.5);
            drawRight(page, row.duration, X_TIME_R, base, font, 8.5);
            drawRight(page, row.pace, X_PACE_R, base, font, 8.5);

            page.drawLine({
                start: { x: X_DATE - 4, y: base - 7 },
                end: { x: PAGE_W - MARGIN + 4, y: base - 7 },
                thickness: 0.5, color: LINE,
            });
            y -= rowH;
            rowsDrawn++;
        }
        y -= 10;
    }

    // ---- footers (every page) ----
    pages.forEach((p, i) => {
        p.drawLine({ start: { x: MARGIN, y: 40 }, end: { x: PAGE_W - MARGIN, y: 40 }, thickness: 0.5, color: LINE });
        p.drawText('RunFlow · runflow.schuelken.uk', { x: MARGIN, y: 28, size: 8, font, color: GRAY });
        const label = String(i + 1);
        p.drawText(label, { x: PAGE_W - MARGIN - font.widthOfTextAtSize(label, 8), y: 28, size: 8, font, color: GRAY });
    });

    return doc.save();
}

export async function buildPlanPdfFor(goal: Parameters<typeof buildExportPlan>[0]): Promise<{ bytes: Uint8Array; fileName: string }> {
    const plan = buildExportPlan(goal);
    return { bytes: await buildPlanPdf(plan), fileName: exportFileName(goal.raceType, 'pdf') };
}
