export const METRICS = {
    CTL_DECAY_DAYS: 42,
    ATL_DECAY_DAYS: 7,
    EASY_TRIMP_WINDOW_DAYS: 7,
    WORKLOAD_RATIO_OPTIMAL_MIN: 0.8,
    WORKLOAD_RATIO_OPTIMAL_MAX: 1.3,
    WORKLOAD_RATIO_DANGER_MIN: 1.5,
};

export const ZONES = {
    DEFAULT_MAX_HR: 185,
    DEFAULT_REST_HR: 60,
};

export const TIME_RANGES = {
    SIX_MONTHS_DAYS: 180,
    NINETY_DAYS: 90,
};
